### ISSUE TITLE
Funcionalidade de cadastro de Usuarios

### ISSUE THREAD

**Issue by pabloo-cunha** [dragonfatec/Projeto-web#34]
## Descrição:
Como Admin quero cadastrar usuários, CR e clientes. Assim eles vão poder acessar o nosso site e lançar suas horas extras e sobreaviso.

## Informações técnicas:
Para o usuário preciso das seguintes informações
- Matricula
- Nome
- Cargo
- CR (A confimar se estara ligado diretamento com o usuario)

**OBS:**  Antes de criar o usuário deve ser gerado automaticamente a sua Matricula e mostrado na tela

**Comment by pabloo-cunha** [comment]
Para o usuário preciso das seguintes informações

- Register (Matricula)
- Name
- Rule (Cargo)
- Results Center (CR - A confimar se estara ligado diretamento com o usuario)
- Status

OBS: Matricula deverá ser gerada automaticamente e exibida na tela. Os status do usuario ao ser criado, como default será "Ativo"

**Comment by LucasOliveira321** [comment]
Foi adicionado esta funcionalidade na classe UserService
