### ISSUE TITLE
Funcionalidade de cadastro de Cliente

### ISSUE THREAD

**Issue by pabloo-cunha** [dragonfatec/Projeto-web#35]
## Descrição:
Como Admin quero cadastrar usuários, CR e clientes. Assim eles vão poder acessar o nosso site e lançar suas horas extras e sobreaviso.

## Informações técnicas:
Para o cliente preciso das seguintes informações
- Empresa
- Razão Social da empresa
- CNPJ

**Comment by pabloo-cunha** [comment]
Para o CR preciso das seguintes informações

Code RS (Results Center)
Name RS
Sigla

OBS: O Codigo do time não pode se repetir. Por hora deixaremos o Codigo CR como "input", mas pensaremos na possibilidade de deixar o sistema gerar um aleatorio

**Comment by LucasOliveira321** [comment]
Foi adicionado essa classe com o atributo status.
