### ISSUE TITLE
Funcionalidade de cadastro de CR

### ISSUE THREAD

**Issue by pabloo-cunha** [dragonfatec/Projeto-web#36]
## Descrição:
Como Admin quero cadastrar usuários, CR e clientes. Assim eles vão poder acessar o nosso site e lançar suas horas extras e sobreaviso.

## Informações técnicas:
Para o CR preciso das seguintes informações
- Codigo CR
- Nome do CR
- Sigla

**Comment by pabloo-cunha** [comment]
Para o CR preciso das seguintes informações

- CodeRs (Results Center)
- NameRs
- Sigla (Sugestao de onibus)

OBS: O Código do time não pode se repetir. Por hora deixaremos o Código CR como "input", mas pensaremos na possibilidade de deixar o sistema gerar um aleatório

**Comment by LucasOliveira321** [comment]
Foi adicionado esta classe com o nome de Rc (Result Center),  adicionando mais o atributo status.
