### ISSUE TITLE
Funcionalidade de cadastro de usuários, clientes e times

### ISSUE THREAD

**Issue by LukasFernando** [dragonfatec/Projeto-web#9]
## Descrição:
Como Admin quero cadastrar usuários, CR e clientes. Assim eles vão poder acessar o nosso site e lançar suas horas extras e sobreaviso.

## Informações técnicas:
Para o usuário preciso das seguintes informações
- Matricula
- Nome
- Cargo
- Status
- CR (A confimar se estara ligado diretamento com o usuario)

**OBS:**  Antes de criar o usuário deve ser gerado automaticamente a sua Matricula e mostrado na tela 

Para o CR preciso das seguintes informações
- Código CR;
- Nome do CR
- Sigla

**OBS:** O Codigo do time não pode se repetir. Por hora <ins>deixaremos o Codigo CR como "input"</ins>, mas pensaremos na possibilidade de deixar o sistema gerar um aleatorio

Para o cliente preciso das seguintes informações
- Empresa
- Razão Social da empresa
- CNPJ

**Comment by LucasOliveira321** [comment]
Foi criado as classes e adicionado os métodos de cadastro no service das entidades.
